{
 "title": "Dingospeed",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "所属环境",
    "query": {
     "query": "label_values(request_total_cnt,namespace)"
    }
   },
   {
    "name": "source",
    "label": "客户端IP",
    "query": {
     "query": "label_values(request_total_cnt,source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "请求总数（个）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, job) (sum(request_total_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求成功数（个）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance, job)(request_success_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求断开数（个）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, job) (request_fail_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "请求拒绝数（个）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, job) (sum(request_too_many_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "下载模型数量（个）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, job) (count(request_model_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "下载数据集数量（个）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, job) (count(request_dataset_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "远程下载流量(MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, job) (request_remote_byte{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"} / 1048576)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "响应流量（MB）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance, job) (request_response_byte{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"} / 1048576)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "请求处理（个）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance, job) (request_total_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"})",
     "legendFormat": "请求总数"
    },
    {
     "expr": "sum by (instance, job) (request_success_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"})",
     "legendFormat": "请求成功数"
    }
   ]
  },
  {
   "title": "正在请求处理（个）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "(sum(request_total_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}) or vector(0)) -\n(sum(request_success_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}) or vector(0)) -\n(sum(request_fail_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}) or vector(0)) -\n(sum(request_too_many_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}) or vector(0))",
     "legendFormat": "正在请求数"
    }
   ]
  },
  {
   "title": "请求异常趋势（个）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (instance, job) (request_too_many_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"})",
     "legendFormat": "请求拒绝数"
    },
    {
     "expr": "sum by (instance, job) (request_fail_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"})",
     "legendFormat": "请求断开数"
    }
   ]
  },
  {
   "title": "模型下载（次）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count by(models) (request_model_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"} > 0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "数据集下载（次）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "count by(datasets) (request_dataset_cnt{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}>0)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "远程下载速率（MB/s）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(request_remote_byte{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}[1m]) / 1048576",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "响应速率(MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(request_response_byte{namespace=~\"^($namespace)$\",instance=\"dingospeed\", source=~\"^($source)$\"}[1m]) / 1048576",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}