// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: manager.proto

package manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 注册请求
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	ManagementUrl string                 `protobuf:"bytes,5,opt,name=managementUrl,proto3" json:"managementUrl,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,6,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *RegisterRequest) GetManagementUrl() string {
	if x != nil {
		return x.ManagementUrl
	}
	return ""
}

func (x *RegisterRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

// 注册响应
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 心跳请求
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	Health        *NodeHealthSnapshot    `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HeartbeatRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HeartbeatRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *HeartbeatRequest) GetHealth() *NodeHealthSnapshot {
	if x != nil {
		return x.Health
	}
	return nil
}

// In-memory observations only; absence means the client does not report health.
type NodeHealthSnapshot struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Version                uint32                   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ProcessId              string                   `protobuf:"bytes,2,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	StartedAt              int64                    `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CollectedAt            int64                    `protobuf:"varint,4,opt,name=collected_at,json=collectedAt,proto3" json:"collected_at,omitempty"`
	HeartbeatPeriodSeconds uint32                   `protobuf:"varint,5,opt,name=heartbeat_period_seconds,json=heartbeatPeriodSeconds,proto3" json:"heartbeat_period_seconds,omitempty"`
	Capabilities           []*CapabilityObservation `protobuf:"bytes,6,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Errors                 []*StorageErrorCount     `protobuf:"bytes,7,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeHealthSnapshot) Reset() {
	*x = NodeHealthSnapshot{}
	mi := &file_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeHealthSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeHealthSnapshot) ProtoMessage() {}

func (x *NodeHealthSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeHealthSnapshot.ProtoReflect.Descriptor instead.
func (*NodeHealthSnapshot) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{3}
}

func (x *NodeHealthSnapshot) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NodeHealthSnapshot) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *NodeHealthSnapshot) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *NodeHealthSnapshot) GetCollectedAt() int64 {
	if x != nil {
		return x.CollectedAt
	}
	return 0
}

func (x *NodeHealthSnapshot) GetHeartbeatPeriodSeconds() uint32 {
	if x != nil {
		return x.HeartbeatPeriodSeconds
	}
	return 0
}

func (x *NodeHealthSnapshot) GetCapabilities() []*CapabilityObservation {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeHealthSnapshot) GetErrors() []*StorageErrorCount {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CapabilityObservation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Capability      string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	State           int32                  `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"` // 0 unknown, 1 observed healthy, 2 suspect, 3 degraded, 4 recovering
	Unresolved      bool                   `protobuf:"varint,3,opt,name=unresolved,proto3" json:"unresolved,omitempty"`
	LastObservation int64                  `protobuf:"varint,4,opt,name=last_observation,json=lastObservation,proto3" json:"last_observation,omitempty"`
	LastFailure     int64                  `protobuf:"varint,5,opt,name=last_failure,json=lastFailure,proto3" json:"last_failure,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilityObservation) Reset() {
	*x = CapabilityObservation{}
	mi := &file_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityObservation) ProtoMessage() {}

func (x *CapabilityObservation) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityObservation.ProtoReflect.Descriptor instead.
func (*CapabilityObservation) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityObservation) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CapabilityObservation) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *CapabilityObservation) GetUnresolved() bool {
	if x != nil {
		return x.Unresolved
	}
	return false
}

func (x *CapabilityObservation) GetLastObservation() int64 {
	if x != nil {
		return x.LastObservation
	}
	return 0
}

func (x *CapabilityObservation) GetLastFailure() int64 {
	if x != nil {
		return x.LastFailure
	}
	return 0
}

type StorageErrorCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     string                 `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // Cumulative within process_id, not an active-failure count.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageErrorCount) Reset() {
	*x = StorageErrorCount{}
	mi := &file_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageErrorCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageErrorCount) ProtoMessage() {}

func (x *StorageErrorCount) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageErrorCount.ProtoReflect.Descriptor instead.
func (*StorageErrorCount) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{5}
}

func (x *StorageErrorCount) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *StorageErrorCount) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *StorageErrorCount) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SchedulerFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      string                 `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Etag          string                 `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	InstanceId    string                 `protobuf:"bytes,6,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	StartPos      int64                  `protobuf:"varint,7,opt,name=startPos,proto3" json:"startPos,omitempty"`
	EndPos        int64                  `protobuf:"varint,8,opt,name=endPos,proto3" json:"endPos,omitempty"`
	FileSize      int64                  `protobuf:"varint,9,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerFileRequest) Reset() {
	*x = SchedulerFileRequest{}
	mi := &file_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerFileRequest) ProtoMessage() {}

func (x *SchedulerFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerFileRequest.ProtoReflect.Descriptor instead.
func (*SchedulerFileRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{6}
}

func (x *SchedulerFileRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *SchedulerFileRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *SchedulerFileRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SchedulerFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SchedulerFileRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *SchedulerFileRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SchedulerFileRequest) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *SchedulerFileRequest) GetEndPos() int64 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *SchedulerFileRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type SyncFileProcessReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FileProcessEntries []*FileProcessEntry    `protobuf:"bytes,1,rep,name=fileProcessEntries,proto3" json:"fileProcessEntries,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncFileProcessReq) Reset() {
	*x = SyncFileProcessReq{}
	mi := &file_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFileProcessReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFileProcessReq) ProtoMessage() {}

func (x *SyncFileProcessReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFileProcessReq.ProtoReflect.Descriptor instead.
func (*SyncFileProcessReq) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{7}
}

func (x *SyncFileProcessReq) GetFileProcessEntries() []*FileProcessEntry {
	if x != nil {
		return x.FileProcessEntries
	}
	return nil
}

type FileProcessEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      string                 `protobuf:"bytes,1,opt,name=dataType,proto3" json:"dataType,omitempty"`
	Org           string                 `protobuf:"bytes,2,opt,name=org,proto3" json:"org,omitempty"`
	Repo          string                 `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Etag          string                 `protobuf:"bytes,5,opt,name=etag,proto3" json:"etag,omitempty"`
	InstanceId    string                 `protobuf:"bytes,6,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	StartPos      int64                  `protobuf:"varint,7,opt,name=startPos,proto3" json:"startPos,omitempty"`
	EndPos        int64                  `protobuf:"varint,8,opt,name=endPos,proto3" json:"endPos,omitempty"`
	FileSize      int64                  `protobuf:"varint,9,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	ProcessId     int64                  `protobuf:"varint,11,opt,name=processId,proto3" json:"processId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileProcessEntry) Reset() {
	*x = FileProcessEntry{}
	mi := &file_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileProcessEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProcessEntry) ProtoMessage() {}

func (x *FileProcessEntry) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProcessEntry.ProtoReflect.Descriptor instead.
func (*FileProcessEntry) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{8}
}

func (x *FileProcessEntry) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *FileProcessEntry) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *FileProcessEntry) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *FileProcessEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileProcessEntry) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *FileProcessEntry) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *FileProcessEntry) GetStartPos() int64 {
	if x != nil {
		return x.StartPos
	}
	return 0
}

func (x *FileProcessEntry) GetEndPos() int64 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *FileProcessEntry) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *FileProcessEntry) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FileProcessEntry) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

// 注册响应
type SchedulerFileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SchedulerType    int32                  `protobuf:"varint,1,opt,name=schedulerType,proto3" json:"schedulerType,omitempty"`
	ProcessId        int64                  `protobuf:"varint,2,opt,name=processId,proto3" json:"processId,omitempty"`
	Host             string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port             int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	MasterInstanceId string                 `protobuf:"bytes,5,opt,name=masterInstanceId,proto3" json:"masterInstanceId,omitempty"`
	MaxOffset        int64                  `protobuf:"varint,6,opt,name=maxOffset,proto3" json:"maxOffset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SchedulerFileResponse) Reset() {
	*x = SchedulerFileResponse{}
	mi := &file_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerFileResponse) ProtoMessage() {}

func (x *SchedulerFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerFileResponse.ProtoReflect.Descriptor instead.
func (*SchedulerFileResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{9}
}

func (x *SchedulerFileResponse) GetSchedulerType() int32 {
	if x != nil {
		return x.SchedulerType
	}
	return 0
}

func (x *SchedulerFileResponse) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *SchedulerFileResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *SchedulerFileResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *SchedulerFileResponse) GetMasterInstanceId() string {
	if x != nil {
		return x.MasterInstanceId
	}
	return ""
}

func (x *SchedulerFileResponse) GetMaxOffset() int64 {
	if x != nil {
		return x.MaxOffset
	}
	return 0
}

type FileProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     int64                  `protobuf:"varint,1,opt,name=processId,proto3" json:"processId,omitempty"`
	StaPos        int64                  `protobuf:"varint,2,opt,name=staPos,proto3" json:"staPos,omitempty"`
	EndPos        int64                  `protobuf:"varint,3,opt,name=endPos,proto3" json:"endPos,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileProcessRequest) Reset() {
	*x = FileProcessRequest{}
	mi := &file_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileProcessRequest) ProtoMessage() {}

func (x *FileProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileProcessRequest.ProtoReflect.Descriptor instead.
func (*FileProcessRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{10}
}

func (x *FileProcessRequest) GetProcessId() int64 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *FileProcessRequest) GetStaPos() int64 {
	if x != nil {
		return x.StaPos
	}
	return 0
}

func (x *FileProcessRequest) GetEndPos() int64 {
	if x != nil {
		return x.EndPos
	}
	return 0
}

func (x *FileProcessRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type DeleteByEtagsAndFieldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	Datatype      string                 `protobuf:"bytes,2,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Org           string                 `protobuf:"bytes,3,opt,name=org,proto3" json:"org,omitempty"`
	Repo          string                 `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	InstanceID    string                 `protobuf:"bytes,6,opt,name=instanceID,proto3" json:"instanceID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByEtagsAndFieldsRequest) Reset() {
	*x = DeleteByEtagsAndFieldsRequest{}
	mi := &file_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByEtagsAndFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByEtagsAndFieldsRequest) ProtoMessage() {}

func (x *DeleteByEtagsAndFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByEtagsAndFieldsRequest.ProtoReflect.Descriptor instead.
func (*DeleteByEtagsAndFieldsRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteByEtagsAndFieldsRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteByEtagsAndFieldsRequest) GetInstanceID() string {
	if x != nil {
		return x.InstanceID
	}
	return ""
}

type CreateCacheJobReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Datatype      string                 `protobuf:"bytes,3,opt,name=datatype,proto3" json:"datatype,omitempty"`
	Org           string                 `protobuf:"bytes,4,opt,name=org,proto3" json:"org,omitempty"`
	Repo          string                 `protobuf:"bytes,5,opt,name=repo,proto3" json:"repo,omitempty"`
	UsedStorage   int64                  `protobuf:"varint,6,opt,name=usedStorage,proto3" json:"usedStorage,omitempty"`
	Commit        string                 `protobuf:"bytes,7,opt,name=commit,proto3" json:"commit,omitempty"`
	Status        int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCacheJobReq) Reset() {
	*x = CreateCacheJobReq{}
	mi := &file_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCacheJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCacheJobReq) ProtoMessage() {}

func (x *CreateCacheJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCacheJobReq.ProtoReflect.Descriptor instead.
func (*CreateCacheJobReq) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCacheJobReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateCacheJobReq) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateCacheJobReq) GetDatatype() string {
	if x != nil {
		return x.Datatype
	}
	return ""
}

func (x *CreateCacheJobReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *CreateCacheJobReq) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CreateCacheJobReq) GetUsedStorage() int64 {
	if x != nil {
		return x.UsedStorage
	}
	return 0
}

func (x *CreateCacheJobReq) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *CreateCacheJobReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 注册响应
type CreateCacheJobResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCacheJobResp) Reset() {
	*x = CreateCacheJobResp{}
	mi := &file_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCacheJobResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCacheJobResp) ProtoMessage() {}

func (x *CreateCacheJobResp) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCacheJobResp.ProtoReflect.Descriptor instead.
func (*CreateCacheJobResp) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCacheJobResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCacheJobStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	InstanceId    string                 `protobuf:"bytes,4,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	Org           string                 `protobuf:"bytes,5,opt,name=org,proto3" json:"org,omitempty"`
	Repo          string                 `protobuf:"bytes,6,opt,name=repo,proto3" json:"repo,omitempty"`
	Process       float32                `protobuf:"fixed32,7,opt,name=process,proto3" json:"process,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCacheJobStatusReq) Reset() {
	*x = UpdateCacheJobStatusReq{}
	mi := &file_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCacheJobStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCacheJobStatusReq) ProtoMessage() {}

func (x *UpdateCacheJobStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCacheJobStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateCacheJobStatusReq) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCacheJobStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCacheJobStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateCacheJobStatusReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *UpdateCacheJobStatusReq) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdateCacheJobStatusReq) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *UpdateCacheJobStatusReq) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *UpdateCacheJobStatusReq) GetProcess() float32 {
	if x != nil {
		return x.Process
	}
	return 0
}

type UpdateRepositoryMountStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRepositoryMountStatusReq) Reset() {
	*x = UpdateRepositoryMountStatusReq{}
	mi := &file_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRepositoryMountStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRepositoryMountStatusReq) ProtoMessage() {}

func (x *UpdateRepositoryMountStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRepositoryMountStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateRepositoryMountStatusReq) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRepositoryMountStatusReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRepositoryMountStatusReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateRepositoryMountStatusReq) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

type IngestRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RepoType      string                 `protobuf:"bytes,3,opt,name=repo_type,json=repoType,proto3" json:"repo_type,omitempty"`
	Repo          string                 `protobuf:"bytes,4,opt,name=repo,proto3" json:"repo,omitempty"`
	Revision      string                 `protobuf:"bytes,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Commit        string                 `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
	Online        bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRepositoryRequest) Reset() {
	*x = IngestRepositoryRequest{}
	mi := &file_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRepositoryRequest) ProtoMessage() {}

func (x *IngestRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRepositoryRequest.ProtoReflect.Descriptor instead.
func (*IngestRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{16}
}

func (x *IngestRepositoryRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *IngestRepositoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IngestRepositoryRequest) GetRepoType() string {
	if x != nil {
		return x.RepoType
	}
	return ""
}

func (x *IngestRepositoryRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *IngestRepositoryRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *IngestRepositoryRequest) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *IngestRepositoryRequest) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type IngestRepositoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepositoryId  int64                  `protobuf:"varint,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	FileCount     int64                  `protobuf:"varint,3,opt,name=file_count,json=fileCount,proto3" json:"file_count,omitempty"`
	UsedStorage   int64                  `protobuf:"varint,4,opt,name=used_storage,json=usedStorage,proto3" json:"used_storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRepositoryResponse) Reset() {
	*x = IngestRepositoryResponse{}
	mi := &file_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRepositoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRepositoryResponse) ProtoMessage() {}

func (x *IngestRepositoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRepositoryResponse.ProtoReflect.Descriptor instead.
func (*IngestRepositoryResponse) Descriptor() ([]byte, []int) {
	return file_manager_proto_rawDescGZIP(), []int{17}
}

func (x *IngestRepositoryResponse) GetRepositoryId() int64 {
	if x != nil {
		return x.RepositoryId
	}
	return 0
}

func (x *IngestRepositoryResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *IngestRepositoryResponse) GetFileCount() int64 {
	if x != nil {
		return x.FileCount
	}
	return 0
}

func (x *IngestRepositoryResponse) GetUsedStorage() int64 {
	if x != nil {
		return x.UsedStorage
	}
	return 0
}

var File_manager_proto protoreflect.FileDescriptor

const file_manager_proto_rawDesc = "" +
	"\n" +
	"\rmanager.proto\x12\amanager\x1a\x1bgoogle/protobuf/empty.proto\"\xb9\x01\n" +
	"\x0fRegisterRequest\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12$\n" +
	"\rmanagementUrl\x18\x05 \x01(\tR\rmanagementUrl\x12 \n" +
	"\vdownloadUrl\x18\x06 \x01(\tR\vdownloadUrl\"<\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x8f\x01\n" +
	"\x10HeartbeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x123\n" +
	"\x06health\x18\x04 \x01(\v2\x1b.manager.NodeHealthSnapshotR\x06health\"\xc1\x02\n" +
	"\x12NodeHealthSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"process_id\x18\x02 \x01(\tR\tprocessId\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcollected_at\x18\x04 \x01(\x03R\vcollectedAt\x128\n" +
	"\x18heartbeat_period_seconds\x18\x05 \x01(\rR\x16heartbeatPeriodSeconds\x12B\n" +
	"\fcapabilities\x18\x06 \x03(\v2\x1e.manager.CapabilityObservationR\fcapabilities\x122\n" +
	"\x06errors\x18\a \x03(\v2\x1a.manager.StorageErrorCountR\x06errors\"\xbb\x01\n" +
	"\x15CapabilityObservation\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x14\n" +
	"\x05state\x18\x02 \x01(\x05R\x05state\x12\x1e\n" +
	"\n" +
	"unresolved\x18\x03 \x01(\bR\n" +
	"unresolved\x12)\n" +
	"\x10last_observation\x18\x04 \x01(\x03R\x0flastObservation\x12!\n" +
	"\flast_failure\x18\x05 \x01(\x03R\vlastFailure\"[\n" +
	"\x11StorageErrorCount\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\tR\toperation\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"\xf0\x01\n" +
	"\x14SchedulerFileRequest\x12\x1a\n" +
	"\bdataType\x18\x01 \x01(\tR\bdataType\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04etag\x18\x05 \x01(\tR\x04etag\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x06 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bstartPos\x18\a \x01(\x03R\bstartPos\x12\x16\n" +
	"\x06endPos\x18\b \x01(\x03R\x06endPos\x12\x1a\n" +
	"\bfileSize\x18\t \x01(\x03R\bfileSize\"_\n" +
	"\x12SyncFileProcessReq\x12I\n" +
	"\x12fileProcessEntries\x18\x01 \x03(\v2\x19.manager.FileProcessEntryR\x12fileProcessEntries\"\xa2\x02\n" +
	"\x10FileProcessEntry\x12\x1a\n" +
	"\bdataType\x18\x01 \x01(\tR\bdataType\x12\x10\n" +
	"\x03org\x18\x02 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x03 \x01(\tR\x04repo\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04etag\x18\x05 \x01(\tR\x04etag\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x06 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bstartPos\x18\a \x01(\x03R\bstartPos\x12\x16\n" +
	"\x06endPos\x18\b \x01(\x03R\x06endPos\x12\x1a\n" +
	"\bfileSize\x18\t \x01(\x03R\bfileSize\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\x1c\n" +
	"\tprocessId\x18\v \x01(\x03R\tprocessId\"\xcd\x01\n" +
	"\x15SchedulerFileResponse\x12$\n" +
	"\rschedulerType\x18\x01 \x01(\x05R\rschedulerType\x12\x1c\n" +
	"\tprocessId\x18\x02 \x01(\x03R\tprocessId\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12*\n" +
	"\x10masterInstanceId\x18\x05 \x01(\tR\x10masterInstanceId\x12\x1c\n" +
	"\tmaxOffset\x18\x06 \x01(\x03R\tmaxOffset\"z\n" +
	"\x12FileProcessRequest\x12\x1c\n" +
	"\tprocessId\x18\x01 \x01(\x03R\tprocessId\x12\x16\n" +
	"\x06staPos\x18\x02 \x01(\x03R\x06staPos\x12\x16\n" +
	"\x06endPos\x18\x03 \x01(\x03R\x06endPos\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\xa9\x01\n" +
	"\x1dDeleteByEtagsAndFieldsRequest\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12\x1a\n" +
	"\bdatatype\x18\x02 \x01(\tR\bdatatype\x12\x10\n" +
	"\x03org\x18\x03 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x04 \x01(\tR\x04repo\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"instanceID\x18\x06 \x01(\tR\n" +
	"instanceID\"\xdb\x01\n" +
	"\x11CreateCacheJobReq\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bdatatype\x18\x03 \x01(\tR\bdatatype\x12\x10\n" +
	"\x03org\x18\x04 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x05 \x01(\tR\x04repo\x12 \n" +
	"\vusedStorage\x18\x06 \x01(\x03R\vusedStorage\x12\x16\n" +
	"\x06commit\x18\a \x01(\tR\x06commit\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"$\n" +
	"\x12CreateCacheJobResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xbd\x01\n" +
	"\x17UpdateCacheJobStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x04 \x01(\tR\n" +
	"instanceId\x12\x10\n" +
	"\x03org\x18\x05 \x01(\tR\x03org\x12\x12\n" +
	"\x04repo\x18\x06 \x01(\tR\x04repo\x12\x18\n" +
	"\aprocess\x18\a \x01(\x02R\aprocess\"d\n" +
	"\x1eUpdateRepositoryMountStatusReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1a\n" +
	"\berrorMsg\x18\x03 \x01(\tR\berrorMsg\"\xd5\x01\n" +
	"\x17IngestRepositoryRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1b\n" +
	"\trepo_type\x18\x03 \x01(\tR\brepoType\x12\x12\n" +
	"\x04repo\x18\x04 \x01(\tR\x04repo\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\tR\brevision\x12\x16\n" +
	"\x06commit\x18\x06 \x01(\tR\x06commit\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\"\x99\x01\n" +
	"\x18IngestRepositoryResponse\x12#\n" +
	"\rrepository_id\x18\x01 \x01(\x03R\frepositoryId\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"file_count\x18\x03 \x01(\x03R\tfileCount\x12!\n" +
	"\fused_storage\x18\x04 \x01(\x03R\vusedStorage2\x9e\x06\n" +
	"\aManager\x12W\n" +
	"\x10IngestRepository\x12 .manager.IngestRepositoryRequest\x1a!.manager.IngestRepositoryResponse\x12A\n" +
	"\bRegister\x12\x18.manager.RegisterRequest\x1a\x19.manager.RegisterResponse\"\x00\x12>\n" +
	"\tHeartbeat\x12\x19.manager.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\rSchedulerFile\x12\x1d.manager.SchedulerFileRequest\x1a\x1e.manager.SchedulerFileResponse\x12H\n" +
	"\x11ReportFileProcess\x12\x1b.manager.FileProcessRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x0fSyncFileProcess\x12\x1b.manager.SyncFileProcessReq\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x16DeleteByEtagsAndFields\x12&.manager.DeleteByEtagsAndFieldsRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x0eCreateCacheJob\x12\x1a.manager.CreateCacheJobReq\x1a\x1b.manager.CreateCacheJobResp\x12P\n" +
	"\x14UpdateCacheJobStatus\x12 .manager.UpdateCacheJobStatusReq\x1a\x16.google.protobuf.Empty\x12^\n" +
	"\x1bUpdateRepositoryMountStatus\x12'.manager.UpdateRepositoryMountStatusReq\x1a\x16.google.protobuf.EmptyB\vZ\t.;managerb\x06proto3"

var (
	file_manager_proto_rawDescOnce sync.Once
	file_manager_proto_rawDescData []byte
)

func file_manager_proto_rawDescGZIP() []byte {
	file_manager_proto_rawDescOnce.Do(func() {
		file_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)))
	})
	return file_manager_proto_rawDescData
}

var file_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_manager_proto_goTypes = []any{
	(*RegisterRequest)(nil),                // 0: manager.RegisterRequest
	(*RegisterResponse)(nil),               // 1: manager.RegisterResponse
	(*HeartbeatRequest)(nil),               // 2: manager.HeartbeatRequest
	(*NodeHealthSnapshot)(nil),             // 3: manager.NodeHealthSnapshot
	(*CapabilityObservation)(nil),          // 4: manager.CapabilityObservation
	(*StorageErrorCount)(nil),              // 5: manager.StorageErrorCount
	(*SchedulerFileRequest)(nil),           // 6: manager.SchedulerFileRequest
	(*SyncFileProcessReq)(nil),             // 7: manager.SyncFileProcessReq
	(*FileProcessEntry)(nil),               // 8: manager.FileProcessEntry
	(*SchedulerFileResponse)(nil),          // 9: manager.SchedulerFileResponse
	(*FileProcessRequest)(nil),             // 10: manager.FileProcessRequest
	(*DeleteByEtagsAndFieldsRequest)(nil),  // 11: manager.DeleteByEtagsAndFieldsRequest
	(*CreateCacheJobReq)(nil),              // 12: manager.CreateCacheJobReq
	(*CreateCacheJobResp)(nil),             // 13: manager.CreateCacheJobResp
	(*UpdateCacheJobStatusReq)(nil),        // 14: manager.UpdateCacheJobStatusReq
	(*UpdateRepositoryMountStatusReq)(nil), // 15: manager.UpdateRepositoryMountStatusReq
	(*IngestRepositoryRequest)(nil),        // 16: manager.IngestRepositoryRequest
	(*IngestRepositoryResponse)(nil),       // 17: manager.IngestRepositoryResponse
	(*emptypb.Empty)(nil),                  // 18: google.protobuf.Empty
}
var file_manager_proto_depIdxs = []int32{
	3,  // 0: manager.HeartbeatRequest.health:type_name -> manager.NodeHealthSnapshot
	4,  // 1: manager.NodeHealthSnapshot.capabilities:type_name -> manager.CapabilityObservation
	5,  // 2: manager.NodeHealthSnapshot.errors:type_name -> manager.StorageErrorCount
	8,  // 3: manager.SyncFileProcessReq.fileProcessEntries:type_name -> manager.FileProcessEntry
	16, // 4: manager.Manager.IngestRepository:input_type -> manager.IngestRepositoryRequest
	0,  // 5: manager.Manager.Register:input_type -> manager.RegisterRequest
	2,  // 6: manager.Manager.Heartbeat:input_type -> manager.HeartbeatRequest
	6,  // 7: manager.Manager.SchedulerFile:input_type -> manager.SchedulerFileRequest
	10, // 8: manager.Manager.ReportFileProcess:input_type -> manager.FileProcessRequest
	7,  // 9: manager.Manager.SyncFileProcess:input_type -> manager.SyncFileProcessReq
	11, // 10: manager.Manager.DeleteByEtagsAndFields:input_type -> manager.DeleteByEtagsAndFieldsRequest
	12, // 11: manager.Manager.CreateCacheJob:input_type -> manager.CreateCacheJobReq
	14, // 12: manager.Manager.UpdateCacheJobStatus:input_type -> manager.UpdateCacheJobStatusReq
	15, // 13: manager.Manager.UpdateRepositoryMountStatus:input_type -> manager.UpdateRepositoryMountStatusReq
	17, // 14: manager.Manager.IngestRepository:output_type -> manager.IngestRepositoryResponse
	1,  // 15: manager.Manager.Register:output_type -> manager.RegisterResponse
	18, // 16: manager.Manager.Heartbeat:output_type -> google.protobuf.Empty
	9,  // 17: manager.Manager.SchedulerFile:output_type -> manager.SchedulerFileResponse
	18, // 18: manager.Manager.ReportFileProcess:output_type -> google.protobuf.Empty
	18, // 19: manager.Manager.SyncFileProcess:output_type -> google.protobuf.Empty
	18, // 20: manager.Manager.DeleteByEtagsAndFields:output_type -> google.protobuf.Empty
	13, // 21: manager.Manager.CreateCacheJob:output_type -> manager.CreateCacheJobResp
	18, // 22: manager.Manager.UpdateCacheJobStatus:output_type -> google.protobuf.Empty
	18, // 23: manager.Manager.UpdateRepositoryMountStatus:output_type -> google.protobuf.Empty
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_manager_proto_init() }
func file_manager_proto_init() {
	if File_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_manager_proto_rawDesc), len(file_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_manager_proto_goTypes,
		DependencyIndexes: file_manager_proto_depIdxs,
		MessageInfos:      file_manager_proto_msgTypes,
	}.Build()
	File_manager_proto = out.File
	file_manager_proto_goTypes = nil
	file_manager_proto_depIdxs = nil
}
